export const detalhes = {
    btnDetalhes: "#root > main > section > section > div > div > div.sc-lnsjTu.kGApzi > div.MuiBox-root.css-8atqhb > div.MuiDataGrid-root.MuiDataGrid-root--densityStandard.MuiDataGrid-withBorderColor.css-l994j > div > div.MuiDataGrid-virtualScroller.css-1pzb349 > div > div > div:nth-child(1) > div:nth-child(6) > button",
    textModalColaborador: "#root > main > section > header > section > div > h1",
    abahardSkills: "#mui-p-81912-T-1",
    trilhaEstagiario: "#mui-p-53525-P-1 > div.sc-jgraLO.ikRqeT.MuiBox-root.css-0 > div > div > div:nth-child(1) > p",
    trilhaPgPrincipal: "#root > main > section > section > div > div > div.sc-lnsjTu.kGApzi > div.MuiBox-root.css-8atqhb > div.MuiDataGrid-root.MuiDataGrid-root--densityStandard.MuiDataGrid-withBorderColor.css-l994j > div > div.MuiDataGrid-virtualScroller.css-1pzb349 > div > div > div:nth-child(1) > div:nth-child(2) > div",
    moduloFrontEnd: "#mui-p-87670-P-1 > ul > li:nth-child(1) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    moduloCss: "#mui-p-87670-P-1 > ul > li:nth-child(2) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    moduloJavaScript: "#mui-p-87670-P-1 > ul > li:nth-child(3) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    moduloReact: "#mui-p-87670-P-1 > ul > li:nth-child(4) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    moduloContextApi: "#mui-p-87670-P-1 > ul > li:nth-child(5) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    softSkillColaboracao: "#mui-p-87670-P-2 > div.sc-ppzwM.hlZSRR > ul > li:nth-child(1) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    softSkillProatividade: "#mui-p-87670-P-2 > div.sc-ppzwM.hlZSRR > ul > li:nth-child(2) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    softSkillTrabalhoEmEquipe: "#mui-p-87670-P-2 > div.sc-ppzwM.hlZSRR > ul > li:nth-child(3) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    softSkillResilienciaeInteligenciaEmocional: "#mui-p-87670-P-2 > div.sc-ppzwM.hlZSRR > ul > li:nth-child(4) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    softSkillComprometimento: "#mui-p-87670-P-2 > div.sc-ppzwM.hlZSRR > ul > li:nth-child(5) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    softSkillGestaoTempoeOrganizacao: "#mui-p-87670-P-2 > div.sc-ppzwM.hlZSRR > ul > li:nth-child(6) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    softSkillFeedbackComportamentalTimeGp: "#mui-p-87670-P-2 > div.sc-ppzwM.hlZSRR > ul > li:nth-child(7) > div > div.MuiListItemText-root.css-1tsvksn > span > div > h2",
    abaSoftSkills: "#mui-p-87670-T-2"
}